import { useEffect, useMemo, useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { useLocation } from 'wouter';
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, HeartHandshake, LoaderCircle, ShieldCheck, Sparkles } from 'lucide-react';
import { getGetCurrentUserQueryKey, sendOtp, verifyIdentity, verifyOtp } from '@workspace/api-client-react';
import { Button } from '@/components/app-shell';

type Role = 'STUDENT' | 'MENTOR' | 'HOD';
const roles = [
  { key: 'STUDENT', label: 'Student', detail: 'Your own attendance, requests, and insights', icon: Sparkles },
  { key: 'MENTOR', label: 'Mentor', detail: 'Students in your care and review actions', icon: HeartHandshake },
  { key: 'HOD', label: 'Head of department', detail: 'Department-wide attendance attention', icon: ShieldCheck },
] as const;

function errorMessage(error: unknown, fallback: string) {
  if (!error || typeof error !== 'object' || !('data' in error)) return fallback;
  const data = error.data;
  return data && typeof data === 'object' && 'error' in data && typeof data.error === 'string' ? data.error : fallback;
}

export default function Login() {
  const [, setLocation] = useLocation();
  const queryClient = useQueryClient();
  const [step, setStep] = useState(1); const [role, setRole] = useState<Role>('STUDENT');
  const [identifier, setIdentifier] = useState(''); const [mobile, setMobile] = useState('');
  const [maskedMobile, setMaskedMobile] = useState(''); const [otp, setOtp] = useState('');
  const [expiresIn, setExpiresIn] = useState(0); const [resendIn, setResendIn] = useState(0);
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (step !== 3) return; const timer = window.setInterval(() => { setExpiresIn(v => Math.max(0, v - 1)); setResendIn(v => Math.max(0, v - 1)); }, 1000); return () => window.clearInterval(timer); }, [step]);
  useEffect(() => { if (step !== 4) return; const timer = window.setTimeout(() => setLocation('/'), 900); return () => window.clearTimeout(timer); }, [step, setLocation]);
  const identityLabel = role === 'STUDENT' ? 'Admission number' : role === 'MENTOR' ? 'Faculty / employee ID' : 'HOD / employee ID';
  const roleLabel = roles.find(item => item.key === role)?.label ?? role;
  const countdown = useMemo(() => `${Math.floor(expiresIn / 60)}:${String(expiresIn % 60).padStart(2, '0')}`, [expiresIn]);
  const submitIdentity = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const identity = await verifyIdentity({ role, identifier, mobile }); const delivery = await sendOtp(); setMaskedMobile(identity.maskedMobile || delivery.maskedMobile); setExpiresIn(delivery.expiresIn); setResendIn(delivery.resendAvailableIn); setOtp(''); setStep(3); } catch (reason) { setError(errorMessage(reason, 'We could not verify those details.')); } finally { setBusy(false); } };
  const resend = async () => { setBusy(true); setError(''); try { const delivery = await sendOtp(); setMaskedMobile(delivery.maskedMobile); setExpiresIn(delivery.expiresIn); setResendIn(delivery.resendAvailableIn); setOtp(''); } catch (reason) { setError(errorMessage(reason, 'We could not send another code.')); } finally { setBusy(false); } };
  const submitOtp = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const user = await verifyOtp({ otp }); queryClient.setQueryData(getGetCurrentUserQueryKey(), user); setStep(4); } catch (reason) { setError(errorMessage(reason, 'We could not verify that code.')); } finally { setBusy(false); } };
  const goBack = () => { setError(''); setStep(value => Math.max(1, value - 1)); };
  return <main className="noise min-h-[100dvh] bg-background"><div className="mx-auto grid min-h-[100dvh] max-w-[1440px] lg:grid-cols-[.86fr_1.14fr]">
    <section className="relative hidden overflow-hidden bg-sidebar p-12 text-sidebar-foreground lg:flex lg:flex-col"><div className="absolute -right-28 top-20 h-80 w-80 rounded-full border-[38px] border-accent/10"/><div className="absolute -bottom-40 -left-20 h-96 w-96 rounded-full border-[1px] border-sidebar-border"/><div className="relative flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-sidebar-primary text-sidebar-primary-foreground"><BookOpen size={20}/></span><span className="font-display text-2xl">attendance</span></div><div className="relative mt-auto max-w-md pb-10"><p className="mb-5 text-[11px] font-bold uppercase tracking-[.22em] text-sidebar-primary">A calmer way to keep track</p><h1 className="font-display text-6xl leading-[.98] tracking-[-.04em]">Your attendance should make sense.</h1><p className="mt-7 max-w-sm text-sm leading-7 text-sidebar-foreground/65">See the whole picture, understand the risk, and know exactly what to do next — without the ERP maze.</p><div className="mt-10 flex gap-8 border-t border-sidebar-border pt-5 text-xs text-sidebar-foreground/60"><span className="flex items-center gap-2"><ShieldCheck size={14} className="text-sidebar-primary"/> Protected</span><span className="flex items-center gap-2"><HeartHandshake size={14} className="text-sidebar-primary"/> Student-first</span></div></div><p className="relative text-[11px] text-sidebar-foreground/40">Attendance Companion · Secure access</p></section>
    <section className="flex items-center justify-center px-5 py-10 sm:px-10"><div className="w-full max-w-[440px] animate-rise-in"><div className="mb-10 flex items-center gap-3 lg:hidden"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary text-primary-foreground"><BookOpen size={19}/></span><span className="font-display text-2xl">attendance</span></div><div className="mb-8 flex items-center justify-between"><p className="text-[11px] font-bold uppercase tracking-[.2em] text-primary">Secure sign in</p><span className="rounded-full bg-secondary px-3 py-1 text-[11px] font-bold text-secondary-foreground">{step} / 4</span></div><div className="mb-9 grid grid-cols-4 gap-2">{[1,2,3,4].map(value => <span key={value} className={`h-1 rounded-full ${value <= step ? 'bg-primary' : 'bg-border'}`}/>)}</div>
    {step === 1 && <><h2 className="font-display text-4xl leading-tight sm:text-5xl">Choose your role.</h2><p className="mt-4 max-w-sm text-sm leading-6 text-muted-foreground">We’ll use your campus identity to open the right workspace.</p><div className="mt-8 space-y-3">{roles.map(({key,label,detail,icon:Icon}) => <button key={key} onClick={() => setRole(key)} data-testid={`button-role-${key.toLowerCase()}`} className={`flex w-full items-center gap-4 rounded-2xl border p-4 text-left transition-all ${role === key ? 'border-primary bg-secondary shadow-sm' : 'border-border bg-card hover:border-primary/35'}`}><span className={`grid h-10 w-10 place-items-center rounded-xl ${role === key ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground'}`}><Icon size={18}/></span><span className="flex-1"><strong className="block text-sm">{label}</strong><span className="mt-0.5 block text-xs text-muted-foreground">{detail}</span></span>{role === key && <CheckCircle2 size={18} className="text-primary"/>}</button>)}</div><Button onClick={() => setStep(2)} className="mt-7 w-full py-3.5" testId="button-continue-role">Continue <ArrowRight size={16}/></Button></>}
    {step === 2 && <><button onClick={goBack} className="mb-5 inline-flex items-center gap-1 text-xs font-semibold text-muted-foreground hover:text-primary"><ArrowLeft size={14}/> Back to role</button><h2 className="font-display text-4xl leading-tight">Confirm your identity.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Signing in as <strong className="text-foreground">{roleLabel}</strong>. Use the mobile number registered with your institution.</p><form onSubmit={submitIdentity} className="mt-7 space-y-4"><label className="block text-xs font-semibold text-foreground">{identityLabel}<input value={identifier} onChange={event => setIdentifier(event.target.value)} required autoComplete="username" data-testid="input-identity-id" className="mt-2 w-full rounded-xl border border-border bg-card px-3 py-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/15" placeholder={role === 'STUDENT' ? 'Enter admission number' : 'Enter employee ID'}/></label><label className="block text-xs font-semibold text-foreground">Registered mobile number<input value={mobile} onChange={event => setMobile(event.target.value)} required inputMode="numeric" autoComplete="tel" data-testid="input-identity-mobile" className="mt-2 w-full rounded-xl border border-border bg-card px-3 py-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/15" placeholder="Enter mobile number"/></label>{error && <p data-testid="status-identity-error" className="text-xs text-destructive">{error}</p>}<Button type="submit" disabled={busy} className="w-full py-3.5" testId="button-verify-identity">{busy ? <><LoaderCircle className="animate-spin" size={16}/> Verifying…</> : <>Continue securely <ArrowRight size={16}/></>}</Button></form></>}
    {step === 3 && <><button onClick={goBack} className="mb-5 inline-flex items-center gap-1 text-xs font-semibold text-muted-foreground hover:text-primary"><ArrowLeft size={14}/> Back to identity</button><h2 className="font-display text-4xl leading-tight">Check your phone.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">We sent a six-digit verification code to <strong className="text-foreground">{maskedMobile}</strong>.</p><form onSubmit={submitOtp} className="mt-7 space-y-4"><label className="block text-xs font-semibold text-foreground">Verification code<input value={otp} onChange={event => setOtp(event.target.value.replace(/\D/g, '').slice(0, 6))} required inputMode="numeric" autoComplete="one-time-code" data-testid="input-otp" className="mt-2 w-full rounded-xl border border-border bg-card px-3 py-3 text-center font-mono text-xl tracking-[.45em] outline-none focus:border-primary focus:ring-2 focus:ring-primary/15" placeholder="••••••"/></label><div className="flex items-center justify-between text-xs"><span className={expiresIn === 0 ? 'text-destructive' : 'text-muted-foreground'}>{expiresIn ? `Code expires in ${countdown}` : 'Code expired'}</span><button type="button" onClick={resend} disabled={busy || resendIn > 0} data-testid="button-resend-otp" className="font-semibold text-primary disabled:text-muted-foreground">{resendIn > 0 ? `Resend in ${resendIn}s` : 'Resend code'}</button></div>{error && <p data-testid="status-otp-error" className="text-xs text-destructive">{error}</p>}<Button type="submit" disabled={busy || otp.length !== 6} className="w-full py-3.5" testId="button-verify-otp">{busy ? <><LoaderCircle className="animate-spin" size={16}/> Verifying…</> : <>Verify & enter workspace <ArrowRight size={16}/></>}</Button></form></>}
    {step === 4 && <div className="py-10 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#dcece2] text-primary"><CheckCircle2 size={29}/></span><p className="mt-7 text-[11px] font-bold uppercase tracking-[.2em] text-primary">Authentication complete</p><h2 className="mt-3 font-display text-4xl">Welcome to your workspace.</h2><p className="mt-3 text-sm text-muted-foreground">Your secure session is ready.</p></div>}</div></section></div></main>;
}
