import fs from "node:fs";
import path from "node:path";
import XLSX from "xlsx";

export interface TimetableSeedRow {
  section: string;
  day_of_week: "MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY";
  start_time: string;
  end_time: string;
  subject_code: string | null;
  subject_name: string;
  batch_type: "ALL" | "LAB" | "PYTHON" | "CLOUD";
  batch: "ALL" | "B1" | "B2" | "B3";
  teacher_initials: string | null;
  teacher_name: string | null;
  room: string;
  lecture_type: "LECTURE" | "LAB" | "WORKSHOP" | "OTHER";
}

// ── CSE-34 Timetable entries (Classroom: AB-108) ──
export const cse34Entries: TimetableSeedRow[] = [
  // ── MONDAY ──
  // 08:50 - 10:30 Parallel Labs (2-period block)
  {
    section: "CSE-34",
    day_of_week: "MONDAY",
    start_time: "08:50",
    end_time: "10:30",
    subject_code: "25CS351",
    subject_name: "Object Oriented Programming Paradigm Lab",
    batch_type: "LAB",
    batch: "B2",
    teacher_initials: "NY",
    teacher_name: "Ms. Nidhi Yadav",
    room: "Lab 31",
    lecture_type: "LAB",
  },
  {
    section: "CSE-34",
    day_of_week: "MONDAY",
    start_time: "08:50",
    end_time: "10:30",
    subject_code: "25VA351",
    subject_name: "Full Stack Web Development",
    batch_type: "LAB",
    batch: "B1",
    teacher_initials: "AK",
    teacher_name: "Arvind Kumar",
    room: "Lab 32",
    lecture_type: "LAB",
  },
  // 10:40 - 11:30
  {
    section: "CSE-34",
    day_of_week: "MONDAY",
    start_time: "10:40",
    end_time: "11:30",
    subject_code: "25CS303",
    subject_name: "Advanced Data Structure",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "MG",
    teacher_name: "Ms. Malvika Gupta",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  // 11:30 - 12:20
  {
    section: "CSE-34",
    day_of_week: "MONDAY",
    start_time: "11:30",
    end_time: "12:20",
    subject_code: "25AS301",
    subject_name: "Applied Maths for Computer Application",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "MPS",
    teacher_name: "Dr. Mahima Poniya Singh",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  // 13:10 - 14:00
  {
    section: "CSE-34",
    day_of_week: "MONDAY",
    start_time: "13:10",
    end_time: "14:00",
    subject_code: "25HU301",
    subject_name: "Universal Human Values",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "SG",
    teacher_name: "Dr. Sunita Goyal",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  // 14:00 - 14:50
  {
    section: "CSE-34",
    day_of_week: "MONDAY",
    start_time: "14:00",
    end_time: "14:50",
    subject_code: "25CS303",
    subject_name: "Advanced Data Structure",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "MG",
    teacher_name: "Ms. Malvika Gupta",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  // 14:50 - 15:40
  {
    section: "CSE-34",
    day_of_week: "MONDAY",
    start_time: "14:50",
    end_time: "15:40",
    subject_code: "25CS302",
    subject_name: "Operating System",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "HSD",
    teacher_name: "Ms. Harsiddhi Singh Dev",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  // 15:40 - 16:30
  {
    section: "CSE-34",
    day_of_week: "MONDAY",
    start_time: "15:40",
    end_time: "16:30",
    subject_code: "25CS301",
    subject_name: "Object Oriented Programming Paradigm",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "NY",
    teacher_name: "Ms. Nidhi Yadav",
    room: "AB-108",
    lecture_type: "LECTURE",
  },

  // ── TUESDAY ──
  // 08:50 - 09:40
  {
    section: "CSE-34",
    day_of_week: "TUESDAY",
    start_time: "08:50",
    end_time: "09:40",
    subject_code: "25CS303",
    subject_name: "Advanced Data Structure",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "MG",
    teacher_name: "Ms. Malvika Gupta",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  // 09:40 - 10:30
  {
    section: "CSE-34",
    day_of_week: "TUESDAY",
    start_time: "09:40",
    end_time: "10:30",
    subject_code: "25AS301",
    subject_name: "Applied Maths for Computer Application",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "MPS",
    teacher_name: "Dr. Mahima Poniya Singh",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  // 10:40 - 11:30
  {
    section: "CSE-34",
    day_of_week: "TUESDAY",
    start_time: "10:40",
    end_time: "11:30",
    subject_code: "25CS301",
    subject_name: "Object Oriented Programming Paradigm",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "NY",
    teacher_name: "Ms. Nidhi Yadav",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  // 11:30 - 12:20
  {
    section: "CSE-34",
    day_of_week: "TUESDAY",
    start_time: "11:30",
    end_time: "12:20",
    subject_code: "25VA309",
    subject_name: "Verbal Ability",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "BC",
    teacher_name: "Bharti Chauhan",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  // 13:10 - 14:00
  {
    section: "CSE-34",
    day_of_week: "TUESDAY",
    start_time: "13:10",
    end_time: "14:00",
    subject_code: "25CS302",
    subject_name: "Operating System",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "HSD",
    teacher_name: "Ms. Harsiddhi Singh Dev",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  // 14:00 - 15:40 Parallel Python & Cloud (2-period block)
  {
    section: "CSE-34",
    day_of_week: "TUESDAY",
    start_time: "14:00",
    end_time: "15:40",
    subject_code: "25VA301",
    subject_name: "Data Visualization using Python",
    batch_type: "PYTHON",
    batch: "B1",
    teacher_initials: "DKM",
    teacher_name: "Mr. D.K Mishra",
    room: "KC-101",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-34",
    day_of_week: "TUESDAY",
    start_time: "14:00",
    end_time: "15:40",
    subject_code: "25VA301",
    subject_name: "Data Visualization using Python",
    batch_type: "PYTHON",
    batch: "B2",
    teacher_initials: "AKD",
    teacher_name: "Dr. Anil Kumar Dubey",
    room: "KC-102",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-34",
    day_of_week: "TUESDAY",
    start_time: "14:00",
    end_time: "15:40",
    subject_code: "25VA301",
    subject_name: "Data Visualization using Python",
    batch_type: "PYTHON",
    batch: "B3",
    teacher_initials: "PKS",
    teacher_name: "Mr. Prashant Kr. Singh",
    room: "AB-107",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-34",
    day_of_week: "TUESDAY",
    start_time: "14:00",
    end_time: "15:40",
    subject_code: "25VA302",
    subject_name: "Cloud Computing",
    batch_type: "CLOUD",
    batch: "B1",
    teacher_initials: "SSI",
    teacher_name: "Ms. Shweta Singh",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-34",
    day_of_week: "TUESDAY",
    start_time: "14:00",
    end_time: "15:40",
    subject_code: "25VA302",
    subject_name: "Cloud Computing",
    batch_type: "CLOUD",
    batch: "B2",
    teacher_initials: "RR",
    teacher_name: "Dr. Rohit Rastogi",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-34",
    day_of_week: "TUESDAY",
    start_time: "14:00",
    end_time: "15:40",
    subject_code: "25VA302",
    subject_name: "Cloud Computing",
    batch_type: "CLOUD",
    batch: "B3",
    teacher_initials: "BS",
    teacher_name: "Ms. Bharti Shukla",
    room: "KC-105",
    lecture_type: "LECTURE",
  },
  // 15:40 - 16:30
  {
    section: "CSE-34",
    day_of_week: "TUESDAY",
    start_time: "15:40",
    end_time: "16:30",
    subject_code: "25VA309",
    subject_name: "Employability Skills",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "MJ",
    teacher_name: "Dr. Mokshi Juyal",
    room: "AB-108",
    lecture_type: "LECTURE",
  },

  // ── WEDNESDAY ──
  // 08:50 - 09:40
  {
    section: "CSE-34",
    day_of_week: "WEDNESDAY",
    start_time: "08:50",
    end_time: "09:40",
    subject_code: "25VA351",
    subject_name: "Full Stack Web Development",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "AK,DK",
    teacher_name: "Arvind Kumar",
    room: "AB-108",
    lecture_type: "WORKSHOP",
  },
  // 09:40 - 10:30
  {
    section: "CSE-34",
    day_of_week: "WEDNESDAY",
    start_time: "09:40",
    end_time: "10:30",
    subject_code: "25AS301",
    subject_name: "Applied Maths for Computer Application",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "MPS",
    teacher_name: "Dr. Mahima Poniya Singh",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  // 10:40 - 12:20 Parallel Labs (2-period block)
  {
    section: "CSE-34",
    day_of_week: "WEDNESDAY",
    start_time: "10:40",
    end_time: "12:20",
    subject_code: "25CS352",
    subject_name: "Operating System Lab",
    batch_type: "LAB",
    batch: "B2",
    teacher_initials: "HSD",
    teacher_name: "Ms. Harsiddhi Singh Dev",
    room: "Lab 33",
    lecture_type: "LAB",
  },
  {
    section: "CSE-34",
    day_of_week: "WEDNESDAY",
    start_time: "10:40",
    end_time: "12:20",
    subject_code: "25CS351",
    subject_name: "Object Oriented Programming Paradigm Lab",
    batch_type: "LAB",
    batch: "B1",
    teacher_initials: "NY",
    teacher_name: "Ms. Nidhi Yadav",
    room: "Lab 32",
    lecture_type: "LAB",
  },
  // 13:10 - 14:00 Parallel Python & Cloud (1-period slot)
  {
    section: "CSE-34",
    day_of_week: "WEDNESDAY",
    start_time: "13:10",
    end_time: "14:00",
    subject_code: "25VA301",
    subject_name: "Data Visualization using Python",
    batch_type: "PYTHON",
    batch: "B1",
    teacher_initials: "DKM",
    teacher_name: "Mr. D.K Mishra",
    room: "KC-101",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-34",
    day_of_week: "WEDNESDAY",
    start_time: "13:10",
    end_time: "14:00",
    subject_code: "25VA301",
    subject_name: "Data Visualization using Python",
    batch_type: "PYTHON",
    batch: "B2",
    teacher_initials: "AKD",
    teacher_name: "Dr. Anil Kumar Dubey",
    room: "KC-102",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-34",
    day_of_week: "WEDNESDAY",
    start_time: "13:10",
    end_time: "14:00",
    subject_code: "25VA301",
    subject_name: "Data Visualization using Python",
    batch_type: "PYTHON",
    batch: "B3",
    teacher_initials: "PKS",
    teacher_name: "Mr. Prashant Kr. Singh",
    room: "AB-107",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-34",
    day_of_week: "WEDNESDAY",
    start_time: "13:10",
    end_time: "14:00",
    subject_code: "25VA302",
    subject_name: "Cloud Computing",
    batch_type: "CLOUD",
    batch: "B1",
    teacher_initials: "SSI",
    teacher_name: "Ms. Shweta Singh",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-34",
    day_of_week: "WEDNESDAY",
    start_time: "13:10",
    end_time: "14:00",
    subject_code: "25VA302",
    subject_name: "Cloud Computing",
    batch_type: "CLOUD",
    batch: "B2",
    teacher_initials: "RR",
    teacher_name: "Dr. Rohit Rastogi",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-34",
    day_of_week: "WEDNESDAY",
    start_time: "13:10",
    end_time: "14:00",
    subject_code: "25VA302",
    subject_name: "Cloud Computing",
    batch_type: "CLOUD",
    batch: "B3",
    teacher_initials: "BS",
    teacher_name: "Ms. Bharti Shukla",
    room: "AB-LG-07",
    lecture_type: "LECTURE",
  },
  // 14:00 - 14:50
  {
    section: "CSE-34",
    day_of_week: "WEDNESDAY",
    start_time: "14:00",
    end_time: "14:50",
    subject_code: "25CS301",
    subject_name: "Object Oriented Programming Paradigm",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "NY",
    teacher_name: "Ms. Nidhi Yadav",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  // 14:50 - 15:40
  {
    section: "CSE-34",
    day_of_week: "WEDNESDAY",
    start_time: "14:50",
    end_time: "15:40",
    subject_code: "25CS303",
    subject_name: "Advanced Data Structure",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "MG",
    teacher_name: "Ms. Malvika Gupta",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  // 15:40 - 16:30
  {
    section: "CSE-34",
    day_of_week: "WEDNESDAY",
    start_time: "15:40",
    end_time: "16:30",
    subject_code: "25CS302",
    subject_name: "Operating System",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "HSD",
    teacher_name: "Ms. Harsiddhi Singh Dev",
    room: "AB-108",
    lecture_type: "LECTURE",
  },

  // ── THURSDAY ──
  // 08:50 - 10:30 Parallel Labs (2-period block)
  {
    section: "CSE-34",
    day_of_week: "THURSDAY",
    start_time: "08:50",
    end_time: "10:30",
    subject_code: "25CS352",
    subject_name: "Operating System Lab",
    batch_type: "LAB",
    batch: "B1",
    teacher_initials: "HSD",
    teacher_name: "Ms. Harsiddhi Singh Dev",
    room: "Lab 33",
    lecture_type: "LAB",
  },
  {
    section: "CSE-34",
    day_of_week: "THURSDAY",
    start_time: "08:50",
    end_time: "10:30",
    subject_code: "25VA351",
    subject_name: "Full Stack Web Development",
    batch_type: "LAB",
    batch: "B2",
    teacher_initials: "AK",
    teacher_name: "Arvind Kumar",
    room: "Lab 34",
    lecture_type: "LAB",
  },
  // 10:40 - 11:30
  {
    section: "CSE-34",
    day_of_week: "THURSDAY",
    start_time: "10:40",
    end_time: "11:30",
    subject_code: "25HU301",
    subject_name: "Universal Human Values",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "SG",
    teacher_name: "Dr. Sunita Goyal",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  // 11:30 - 12:20
  {
    section: "CSE-34",
    day_of_week: "THURSDAY",
    start_time: "11:30",
    end_time: "12:20",
    subject_code: "25CS303",
    subject_name: "Advanced Data Structure",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "MG",
    teacher_name: "Ms. Malvika Gupta",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  // 13:10 - 14:00
  {
    section: "CSE-34",
    day_of_week: "THURSDAY",
    start_time: "13:10",
    end_time: "14:00",
    subject_code: "25CS303",
    subject_name: "Advanced Data Structure",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "MG",
    teacher_name: "Ms. Malvika Gupta",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  // 14:00 - 14:50
  {
    section: "CSE-34",
    day_of_week: "THURSDAY",
    start_time: "14:00",
    end_time: "14:50",
    subject_code: "25CS301",
    subject_name: "Object Oriented Programming Paradigm",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "NY",
    teacher_name: "Ms. Nidhi Yadav",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  // 14:50 - 15:40
  {
    section: "CSE-34",
    day_of_week: "THURSDAY",
    start_time: "14:50",
    end_time: "15:40",
    subject_code: "25AS301",
    subject_name: "Applied Maths for Computer Application",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "MPS",
    teacher_name: "Dr. Mahima Poniya Singh",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  // 15:40 - 16:30
  {
    section: "CSE-34",
    day_of_week: "THURSDAY",
    start_time: "15:40",
    end_time: "16:30",
    subject_code: null,
    subject_name: "Holistic skill & Innovation III",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "MG,NY",
    teacher_name: "Ms. Malvika Gupta, Ms. Nidhi Yadav",
    room: "AB-108",
    lecture_type: "OTHER",
  },

  // ── FRIDAY ──
  // 08:50 - 10:30 Parallel Python & Cloud (2-period block)
  {
    section: "CSE-34",
    day_of_week: "FRIDAY",
    start_time: "08:50",
    end_time: "10:30",
    subject_code: "25VA301",
    subject_name: "Data Visualization using Python",
    batch_type: "PYTHON",
    batch: "B1",
    teacher_initials: "DKM",
    teacher_name: "Mr. D.K Mishra",
    room: "KC-101",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-34",
    day_of_week: "FRIDAY",
    start_time: "08:50",
    end_time: "10:30",
    subject_code: "25VA301",
    subject_name: "Data Visualization using Python",
    batch_type: "PYTHON",
    batch: "B2",
    teacher_initials: "AKD",
    teacher_name: "Dr. Anil Kumar Dubey",
    room: "KC-102",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-34",
    day_of_week: "FRIDAY",
    start_time: "08:50",
    end_time: "10:30",
    subject_code: "25VA301",
    subject_name: "Data Visualization using Python",
    batch_type: "PYTHON",
    batch: "B3",
    teacher_initials: "PKS",
    teacher_name: "Mr. Prashant Kr. Singh",
    room: "AB-107",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-34",
    day_of_week: "FRIDAY",
    start_time: "08:50",
    end_time: "10:30",
    subject_code: "25VA302",
    subject_name: "Cloud Computing",
    batch_type: "CLOUD",
    batch: "B1",
    teacher_initials: "SSI",
    teacher_name: "Ms. Shweta Singh",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-34",
    day_of_week: "FRIDAY",
    start_time: "08:50",
    end_time: "10:30",
    subject_code: "25VA302",
    subject_name: "Cloud Computing",
    batch_type: "CLOUD",
    batch: "B2",
    teacher_initials: "RR",
    teacher_name: "Dr. Rohit Rastogi",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-34",
    day_of_week: "FRIDAY",
    start_time: "08:50",
    end_time: "10:30",
    subject_code: "25VA302",
    subject_name: "Cloud Computing",
    batch_type: "CLOUD",
    batch: "B3",
    teacher_initials: "BS",
    teacher_name: "Ms. Bharti Shukla",
    room: "AB-LG-08",
    lecture_type: "LECTURE",
  },
  // 10:40 - 11:30
  {
    section: "CSE-34",
    day_of_week: "FRIDAY",
    start_time: "10:40",
    end_time: "11:30",
    subject_code: "25VA351",
    subject_name: "Full Stack Web Development",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "AK,DK",
    teacher_name: "Arvind Kumar",
    room: "AB-108",
    lecture_type: "WORKSHOP",
  },
  // 11:30 - 12:20
  {
    section: "CSE-34",
    day_of_week: "FRIDAY",
    start_time: "11:30",
    end_time: "12:20",
    subject_code: "25HU301",
    subject_name: "Universal Human Values",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "SG",
    teacher_name: "Dr. Sunita Goyal",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  // 13:10 - 14:00
  {
    section: "CSE-34",
    day_of_week: "FRIDAY",
    start_time: "13:10",
    end_time: "14:00",
    subject_code: "25CS302",
    subject_name: "Operating System",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "HSD",
    teacher_name: "Ms. Harsiddhi Singh Dev",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  // 14:00 - 14:50
  {
    section: "CSE-34",
    day_of_week: "FRIDAY",
    start_time: "14:00",
    end_time: "14:50",
    subject_code: "25AS301",
    subject_name: "Applied Maths for Computer Application",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "MPS",
    teacher_name: "Dr. Mahima Poniya Singh",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  // 14:50 - 16:30 (2-period ADS Lab)
  {
    section: "CSE-34",
    day_of_week: "FRIDAY",
    start_time: "14:50",
    end_time: "16:30",
    subject_code: "25CS353",
    subject_name: "Advanced Data Structure Lab",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "MG",
    teacher_name: "Ms. Malvika Gupta",
    room: "Lab 33",
    lecture_type: "LAB",
  },
];

// ── CSE-35 Timetable entries (Classroom: AB-109) ──
export const cse35Entries: TimetableSeedRow[] = [
  // ── MONDAY ──
  // 08:50 - 09:40
  {
    section: "CSE-35",
    day_of_week: "MONDAY",
    start_time: "08:50",
    end_time: "09:40",
    subject_code: "25CS303",
    subject_name: "Advanced Data Structure",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "AKS",
    teacher_name: "Mr. Akhilesh Kr. Srivastava",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  // 09:40 - 10:30
  {
    section: "CSE-35",
    day_of_week: "MONDAY",
    start_time: "09:40",
    end_time: "10:30",
    subject_code: "25VA309",
    subject_name: "Verbal Ability",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "BC",
    teacher_name: "Bharti Chauhan",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  // 10:40 - 11:30
  {
    section: "CSE-35",
    day_of_week: "MONDAY",
    start_time: "10:40",
    end_time: "11:30",
    subject_code: "25AS301",
    subject_name: "Applied Maths for Computer Application",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "MPS",
    teacher_name: "Dr. Mahima Poniya Singh",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  // 11:30 - 12:20
  {
    section: "CSE-35",
    day_of_week: "MONDAY",
    start_time: "11:30",
    end_time: "12:20",
    subject_code: "25CS303",
    subject_name: "Advanced Data Structure",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "AKS",
    teacher_name: "Mr. Akhilesh Kr. Srivastava",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  // 13:10 - 14:00
  {
    section: "CSE-35",
    day_of_week: "MONDAY",
    start_time: "13:10",
    end_time: "14:00",
    subject_code: "25HU301",
    subject_name: "Universal Human Values",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "AU",
    teacher_name: "Ms. Anupriya",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  // 14:00 - 14:50
  {
    section: "CSE-35",
    day_of_week: "MONDAY",
    start_time: "14:00",
    end_time: "14:50",
    subject_code: "25CS301",
    subject_name: "Object Oriented Programming Paradigm",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "NY",
    teacher_name: "Ms. Nidhi Yadav",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  // 14:50 - 15:40
  {
    section: "CSE-35",
    day_of_week: "MONDAY",
    start_time: "14:50",
    end_time: "15:40",
    subject_code: "25CS302",
    subject_name: "Operating System",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "BS",
    teacher_name: "Ms. Bharti Shukla",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  // 15:40 - 16:30
  {
    section: "CSE-35",
    day_of_week: "MONDAY",
    start_time: "15:40",
    end_time: "16:30",
    subject_code: null,
    subject_name: "Holistic skill & Innovation III",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "BS,DKM",
    teacher_name: "Ms. Bharti Shukla, Mr. D.K Mishra",
    room: "AB-109",
    lecture_type: "OTHER",
  },

  // ── TUESDAY ──
  // 08:50 - 09:40
  {
    section: "CSE-35",
    day_of_week: "TUESDAY",
    start_time: "08:50",
    end_time: "09:40",
    subject_code: "25CS301",
    subject_name: "Object Oriented Programming Paradigm",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "NY",
    teacher_name: "Ms. Nidhi Yadav",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  // 09:40 - 10:30
  {
    section: "CSE-35",
    day_of_week: "TUESDAY",
    start_time: "09:40",
    end_time: "10:30",
    subject_code: "25CS303",
    subject_name: "Advanced Data Structure",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "AKS",
    teacher_name: "Mr. Akhilesh Kr. Srivastava",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  // 10:40 - 11:30
  {
    section: "CSE-35",
    day_of_week: "TUESDAY",
    start_time: "10:40",
    end_time: "11:30",
    subject_code: "25AS301",
    subject_name: "Applied Maths for Computer Application",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "MPS",
    teacher_name: "Dr. Mahima Poniya Singh",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  // 11:30 - 12:20
  {
    section: "CSE-35",
    day_of_week: "TUESDAY",
    start_time: "11:30",
    end_time: "12:20",
    subject_code: "25CS303",
    subject_name: "Advanced Data Structure",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "AKS",
    teacher_name: "Mr. Akhilesh Kr. Srivastava",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  // 13:10 - 14:00
  {
    section: "CSE-35",
    day_of_week: "TUESDAY",
    start_time: "13:10",
    end_time: "14:00",
    subject_code: "25HU301",
    subject_name: "Universal Human Values",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "AU",
    teacher_name: "Ms. Anupriya",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  // 14:00 - 15:40 Parallel Python & Cloud (2-period block)
  {
    section: "CSE-35",
    day_of_week: "TUESDAY",
    start_time: "14:00",
    end_time: "15:40",
    subject_code: "25VA301",
    subject_name: "Data Visualization using Python",
    batch_type: "PYTHON",
    batch: "B1",
    teacher_initials: "DKM",
    teacher_name: "Mr. D.K Mishra",
    room: "KC-101",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-35",
    day_of_week: "TUESDAY",
    start_time: "14:00",
    end_time: "15:40",
    subject_code: "25VA301",
    subject_name: "Data Visualization using Python",
    batch_type: "PYTHON",
    batch: "B2",
    teacher_initials: "AKD",
    teacher_name: "Dr. Anil Kumar Dubey",
    room: "KC-102",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-35",
    day_of_week: "TUESDAY",
    start_time: "14:00",
    end_time: "15:40",
    subject_code: "25VA301",
    subject_name: "Data Visualization using Python",
    batch_type: "PYTHON",
    batch: "B3",
    teacher_initials: "PKS",
    teacher_name: "Mr. Prashant Kr. Singh",
    room: "AB-107",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-35",
    day_of_week: "TUESDAY",
    start_time: "14:00",
    end_time: "15:40",
    subject_code: "25VA302",
    subject_name: "Cloud Computing",
    batch_type: "CLOUD",
    batch: "B1",
    teacher_initials: "SSI",
    teacher_name: "Ms. Shweta Singh",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-35",
    day_of_week: "TUESDAY",
    start_time: "14:00",
    end_time: "15:40",
    subject_code: "25VA302",
    subject_name: "Cloud Computing",
    batch_type: "CLOUD",
    batch: "B2",
    teacher_initials: "RR",
    teacher_name: "Dr. Rohit Rastogi",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-35",
    day_of_week: "TUESDAY",
    start_time: "14:00",
    end_time: "15:40",
    subject_code: "25VA302",
    subject_name: "Cloud Computing",
    batch_type: "CLOUD",
    batch: "B3",
    teacher_initials: "BS",
    teacher_name: "Ms. Bharti Shukla",
    room: "KC-105",
    lecture_type: "LECTURE",
  },
  // 15:40 - 16:30 Parallel Lab (1-period slot)
  {
    section: "CSE-35",
    day_of_week: "TUESDAY",
    start_time: "15:40",
    end_time: "16:30",
    subject_code: "25CS351",
    subject_name: "Object Oriented Programming Paradigm Lab",
    batch_type: "LAB",
    batch: "B2",
    teacher_initials: "NY",
    teacher_name: "Ms. Nidhi Yadav",
    room: "Lab 31",
    lecture_type: "LAB",
  },
  {
    section: "CSE-35",
    day_of_week: "TUESDAY",
    start_time: "15:40",
    end_time: "16:30",
    subject_code: "25VA351",
    subject_name: "Full Stack Web Development",
    batch_type: "LAB",
    batch: "B1",
    teacher_initials: "VM",
    teacher_name: "Mr. Vikas Maurya",
    room: "Lab 32",
    lecture_type: "LAB",
  },

  // ── WEDNESDAY ──
  // 08:50 - 10:30 Parallel Labs (2-period block)
  {
    section: "CSE-35",
    day_of_week: "WEDNESDAY",
    start_time: "08:50",
    end_time: "10:30",
    subject_code: "25CS352",
    subject_name: "Operating System Lab",
    batch_type: "LAB",
    batch: "B1",
    teacher_initials: "BS",
    teacher_name: "Ms. Bharti Shukla",
    room: "Lab 31",
    lecture_type: "LAB",
  },
  {
    section: "CSE-35",
    day_of_week: "WEDNESDAY",
    start_time: "08:50",
    end_time: "10:30",
    subject_code: "25VA351",
    subject_name: "Full Stack Web Development",
    batch_type: "LAB",
    batch: "B2",
    teacher_initials: "VM",
    teacher_name: "Mr. Vikas Maurya",
    room: "Lab 32",
    lecture_type: "LAB",
  },
  // 10:40 - 11:30
  {
    section: "CSE-35",
    day_of_week: "WEDNESDAY",
    start_time: "10:40",
    end_time: "11:30",
    subject_code: "25CS302",
    subject_name: "Operating System",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "BS",
    teacher_name: "Ms. Bharti Shukla",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  // 11:30 - 12:20
  {
    section: "CSE-35",
    day_of_week: "WEDNESDAY",
    start_time: "11:30",
    end_time: "12:20",
    subject_code: "25CS303",
    subject_name: "Advanced Data Structure",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "AKS",
    teacher_name: "Mr. Akhilesh Kr. Srivastava",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  // 13:10 - 14:00 Parallel Python & Cloud (1-period slot)
  {
    section: "CSE-35",
    day_of_week: "WEDNESDAY",
    start_time: "13:10",
    end_time: "14:00",
    subject_code: "25VA301",
    subject_name: "Data Visualization using Python",
    batch_type: "PYTHON",
    batch: "B1",
    teacher_initials: "DKM",
    teacher_name: "Mr. D.K Mishra",
    room: "KC-101",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-35",
    day_of_week: "WEDNESDAY",
    start_time: "13:10",
    end_time: "14:00",
    subject_code: "25VA301",
    subject_name: "Data Visualization using Python",
    batch_type: "PYTHON",
    batch: "B2",
    teacher_initials: "AKD",
    teacher_name: "Dr. Anil Kumar Dubey",
    room: "KC-102",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-35",
    day_of_week: "WEDNESDAY",
    start_time: "13:10",
    end_time: "14:00",
    subject_code: "25VA301",
    subject_name: "Data Visualization using Python",
    batch_type: "PYTHON",
    batch: "B3",
    teacher_initials: "PKS",
    teacher_name: "Mr. Prashant Kr. Singh",
    room: "AB-107",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-35",
    day_of_week: "WEDNESDAY",
    start_time: "13:10",
    end_time: "14:00",
    subject_code: "25VA302",
    subject_name: "Cloud Computing",
    batch_type: "CLOUD",
    batch: "B1",
    teacher_initials: "SSI",
    teacher_name: "Ms. Shweta Singh",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-35",
    day_of_week: "WEDNESDAY",
    start_time: "13:10",
    end_time: "14:00",
    subject_code: "25VA302",
    subject_name: "Cloud Computing",
    batch_type: "CLOUD",
    batch: "B2",
    teacher_initials: "RR",
    teacher_name: "Dr. Rohit Rastogi",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-35",
    day_of_week: "WEDNESDAY",
    start_time: "13:10",
    end_time: "14:00",
    subject_code: "25VA302",
    subject_name: "Cloud Computing",
    batch_type: "CLOUD",
    batch: "B3",
    teacher_initials: "BS",
    teacher_name: "Ms. Bharti Shukla",
    room: "AB-LG-07",
    lecture_type: "LECTURE",
  },
  // 14:00 - 14:50
  {
    section: "CSE-35",
    day_of_week: "WEDNESDAY",
    start_time: "14:00",
    end_time: "14:50",
    subject_code: "25AS301",
    subject_name: "Applied Maths for Computer Application",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "MPS",
    teacher_name: "Dr. Mahima Poniya Singh",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  // 14:50 - 16:30 (2-period block)
  {
    section: "CSE-35",
    day_of_week: "WEDNESDAY",
    start_time: "14:50",
    end_time: "16:30",
    subject_code: "25VA309",
    subject_name: "Employability Skills",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "MJ",
    teacher_name: "Dr. Mokshi Juyal",
    room: "AB-109",
    lecture_type: "LECTURE",
  },

  // ── THURSDAY ──
  // 08:50 - 10:30 Parallel Labs (2-period block)
  {
    section: "CSE-35",
    day_of_week: "THURSDAY",
    start_time: "08:50",
    end_time: "10:30",
    subject_code: "25CS352",
    subject_name: "Operating System Lab",
    batch_type: "LAB",
    batch: "B2",
    teacher_initials: "BS",
    teacher_name: "Ms. Bharti Shukla",
    room: "Lab 31",
    lecture_type: "LAB",
  },
  {
    section: "CSE-35",
    day_of_week: "THURSDAY",
    start_time: "08:50",
    end_time: "10:30",
    subject_code: "25CS351",
    subject_name: "Object Oriented Programming Paradigm Lab",
    batch_type: "LAB",
    batch: "B1",
    teacher_initials: "NY",
    teacher_name: "Ms. Nidhi Yadav",
    room: "Lab 32",
    lecture_type: "LAB",
  },
  // 10:40 - 11:30 (ADS Lab 1 hr)
  {
    section: "CSE-35",
    day_of_week: "THURSDAY",
    start_time: "10:40",
    end_time: "11:30",
    subject_code: "25CS353",
    subject_name: "Advanced Data Structure Lab",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "AKS",
    teacher_name: "Mr. Akhilesh Kr. Srivastava",
    room: "Lab 33",
    lecture_type: "LAB",
  },
  // 11:30 - 12:20
  {
    section: "CSE-35",
    day_of_week: "THURSDAY",
    start_time: "11:30",
    end_time: "12:20",
    subject_code: "25AS301",
    subject_name: "Applied Maths for Computer Application",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "MPS",
    teacher_name: "Dr. Mahima Poniya Singh",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  // 13:10 - 14:00
  {
    section: "CSE-35",
    day_of_week: "THURSDAY",
    start_time: "13:10",
    end_time: "14:00",
    subject_code: "25CS301",
    subject_name: "Object Oriented Programming Paradigm",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "NY",
    teacher_name: "Ms. Nidhi Yadav",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  // 14:00 - 14:50
  {
    section: "CSE-35",
    day_of_week: "THURSDAY",
    start_time: "14:00",
    end_time: "14:50",
    subject_code: "25CS302",
    subject_name: "Operating System",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "BS",
    teacher_name: "Ms. Bharti Shukla",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  // 14:50 - 15:40
  {
    section: "CSE-35",
    day_of_week: "THURSDAY",
    start_time: "14:50",
    end_time: "15:40",
    subject_code: "25HU301",
    subject_name: "Universal Human Values",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "AU",
    teacher_name: "Ms. Anupriya",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  // 15:40 - 16:30
  {
    section: "CSE-35",
    day_of_week: "THURSDAY",
    start_time: "15:40",
    end_time: "16:30",
    subject_code: "25CS303",
    subject_name: "Advanced Data Structure",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "AKS",
    teacher_name: "Mr. Akhilesh Kr. Srivastava",
    room: "AB-109",
    lecture_type: "LECTURE",
  },

  // ── FRIDAY ──
  // 08:50 - 10:30 Parallel Python & Cloud (2-period block)
  {
    section: "CSE-35",
    day_of_week: "FRIDAY",
    start_time: "08:50",
    end_time: "10:30",
    subject_code: "25VA301",
    subject_name: "Data Visualization using Python",
    batch_type: "PYTHON",
    batch: "B1",
    teacher_initials: "DKM",
    teacher_name: "Mr. D.K Mishra",
    room: "KC-101",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-35",
    day_of_week: "FRIDAY",
    start_time: "08:50",
    end_time: "10:30",
    subject_code: "25VA301",
    subject_name: "Data Visualization using Python",
    batch_type: "PYTHON",
    batch: "B2",
    teacher_initials: "AKD",
    teacher_name: "Dr. Anil Kumar Dubey",
    room: "KC-102",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-35",
    day_of_week: "FRIDAY",
    start_time: "08:50",
    end_time: "10:30",
    subject_code: "25VA301",
    subject_name: "Data Visualization using Python",
    batch_type: "PYTHON",
    batch: "B3",
    teacher_initials: "PKS",
    teacher_name: "Mr. Prashant Kr. Singh",
    room: "AB-107",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-35",
    day_of_week: "FRIDAY",
    start_time: "08:50",
    end_time: "10:30",
    subject_code: "25VA302",
    subject_name: "Cloud Computing",
    batch_type: "CLOUD",
    batch: "B1",
    teacher_initials: "SSI",
    teacher_name: "Ms. Shweta Singh",
    room: "AB-108",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-35",
    day_of_week: "FRIDAY",
    start_time: "08:50",
    end_time: "10:30",
    subject_code: "25VA302",
    subject_name: "Cloud Computing",
    batch_type: "CLOUD",
    batch: "B2",
    teacher_initials: "RR",
    teacher_name: "Dr. Rohit Rastogi",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  {
    section: "CSE-35",
    day_of_week: "FRIDAY",
    start_time: "08:50",
    end_time: "10:30",
    subject_code: "25VA302",
    subject_name: "Cloud Computing",
    batch_type: "CLOUD",
    batch: "B3",
    teacher_initials: "BS",
    teacher_name: "Ms. Bharti Shukla",
    room: "AB-LG-08",
    lecture_type: "LECTURE",
  },
  // 10:40 - 11:30 (ADS Lab 1 hr)
  {
    section: "CSE-35",
    day_of_week: "FRIDAY",
    start_time: "10:40",
    end_time: "11:30",
    subject_code: "25CS353",
    subject_name: "Advanced Data Structure Lab",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "AKS",
    teacher_name: "Mr. Akhilesh Kr. Srivastava",
    room: "Lab 33",
    lecture_type: "LAB",
  },
  // 11:30 - 12:20
  {
    section: "CSE-35",
    day_of_week: "FRIDAY",
    start_time: "11:30",
    end_time: "12:20",
    subject_code: "25AS301",
    subject_name: "Applied Maths for Computer Application",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "MPS",
    teacher_name: "Dr. Mahima Poniya Singh",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  // 13:10 - 14:50 (FSD Workshop 2-period block)
  {
    section: "CSE-35",
    day_of_week: "FRIDAY",
    start_time: "13:10",
    end_time: "14:50",
    subject_code: "25VA351",
    subject_name: "Full Stack Web Development",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "AK,DK",
    teacher_name: "Arvind Kumar",
    room: "Lab 34",
    lecture_type: "WORKSHOP",
  },
  // 14:50 - 15:40
  {
    section: "CSE-35",
    day_of_week: "FRIDAY",
    start_time: "14:50",
    end_time: "15:40",
    subject_code: "25CS301",
    subject_name: "Object Oriented Programming Paradigm",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "NY",
    teacher_name: "Ms. Nidhi Yadav",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
  // 15:40 - 16:30
  {
    section: "CSE-35",
    day_of_week: "FRIDAY",
    start_time: "15:40",
    end_time: "16:30",
    subject_code: "25CS302",
    subject_name: "Operating System",
    batch_type: "ALL",
    batch: "ALL",
    teacher_initials: "BS",
    teacher_name: "Ms. Bharti Shukla",
    room: "AB-109",
    lecture_type: "LECTURE",
  },
];

export function generateSeedWorkbook(): XLSX.WorkBook {
  const wb = XLSX.utils.book_new();

  const cse34Sheet = XLSX.utils.json_to_sheet(cse34Entries);
  const cse35Sheet = XLSX.utils.json_to_sheet(cse35Entries);
  const allEntriesSheet = XLSX.utils.json_to_sheet([...cse34Entries, ...cse35Entries]);

  XLSX.utils.book_append_sheet(wb, allEntriesSheet, "All Entries");
  XLSX.utils.book_append_sheet(wb, cse34Sheet, "CSE-34");
  XLSX.utils.book_append_sheet(wb, cse35Sheet, "CSE-35");

  return wb;
}

if (process.argv[1] && process.argv[1].includes("generate-timetable-seed")) {
  const targetDir = path.resolve(process.cwd(), "../../data/seed");
  const fallbackDir = path.resolve(process.cwd(), "data/seed");
  const dir = fs.existsSync(targetDir) ? targetDir : fallbackDir;
  const filePath = path.join(dir, "timetable_seed.xlsx");

  const wb = generateSeedWorkbook();
  XLSX.writeFile(wb, filePath);
  console.log(`Generated ${filePath} with:`);
  console.log(`- CSE-34 entries: ${cse34Entries.length}`);
  console.log(`- CSE-35 entries: ${cse35Entries.length}`);
  console.log(`- Total entries: ${cse34Entries.length + cse35Entries.length}`);
}
